### PR TITLE
Broadcom Product Scripts

### PR DESCRIPTION
**Pull request by MikeBauerCA**
This PR expands the repository to include all Broadcom Product Scripts rather than just those that relate to Zowe.

Once merged, the repository name should be changed to `broadcom-product-scripts`.

### CODE REVIEW

**Comment by vaughnmarshall** [comment]
One thought - this will break a bunch of blog links.  Are all the authors aware or is there a clever way to make this preserve old links?

**Comment by MikeBauerCA** [comment]
@vaughnmarshall GitHub should automatically redirect links to accommodate the repository name change. However, if folks were linking to the Gen project specifically, this may be broken due to the name change (CA Gen -> Gen) and moving the project from under the Endevor directory to under the Gen directory. We will need to update one such link in this [communities announcement](https://community.broadcom.com/mainframesoftware/communities/community-home/digestviewer/viewthread?GroupId=1513&MessageKey=23cfac5b-1c00-42a9-b9be-75cd5ad07af3&CommunityKey=4182c217-4789-4997-8f22-87de25983f6e&tab=digestviewer).

**Comment by vaughnmarshall** [comment]
What about links to source code in the repos?

**Comment by MikeBauerCA** [comment]
@vaughnmarshall the redirect would cover all paths. Unfortunately, this PR does change the "ca-endevor" folder to just "endevor" which would result in broken links.

**Comment by vaughnmarshall** [comment]
Ok - I will let Dan Walther know so he can update blogs.

**Review by vaughnmarshall — APPROVED** [review]

**Pull request merged**
